name: Production Deploy
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
on:
  workflow_dispatch:
  push:
    branches:
      - live
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: List current folder
        run: ls -la
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --prefer-dist --ignore-platform-reqs
      - name: List current folder
        run: ls -la
