name: Production Deploy
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
on:
  workflow_dispatch:
  push:
    branches:
      - live
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup PHP 7.3
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.3'
      - name: List current folder
        run: ls -la
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --prefer-dist --ignore-platform-reqs
      - name: List current folder
        run: ls -la
      - name: Run Unit tests
        run: ./vendor/bin/phpunit
      - name: Create release tag
        run: git tag 'live_release_v1'
      - name: Push git tag
        run: git push origin live_release_v1